//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisksizeWatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DisksizeWatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bytes ähnelt.
        /// </summary>
        internal static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap decimal_separator_16 {
            get {
                object obj = ResourceManager.GetObject("decimal_separator_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_cancel_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow-cancel-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_disk_space_32 {
            get {
                object obj = ResourceManager.GetObject("fatcow-disk-space-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_drive_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow-drive-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_drive_cd_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow-drive-cd-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_drive_disk_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow-drive-disk-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_drive_network_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow-drive-network-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_infomation_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow-infomation-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_tick_octagon_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow-tick-octagon-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_script_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow-script-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_wrench_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow-wrench-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gigabytes ähnelt.
        /// </summary>
        internal static string gigabytes {
            get {
                return ResourceManager.GetString("gigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die kilobytes ähnelt.
        /// </summary>
        internal static string kilobytes {
            get {
                return ResourceManager.GetString("kilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die megabytes ähnelt.
        /// </summary>
        internal static string megabytes {
            get {
                return ResourceManager.GetString("megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F0 ähnelt.
        /// </summary>
        internal static string numberformatF0 {
            get {
                return ResourceManager.GetString("numberformatF0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F1 ähnelt.
        /// </summary>
        internal static string numberformatF1 {
            get {
                return ResourceManager.GetString("numberformatF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F2 ähnelt.
        /// </summary>
        internal static string numberformatF2 {
            get {
                return ResourceManager.GetString("numberformatF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F3 ähnelt.
        /// </summary>
        internal static string numberformatF3 {
            get {
                return ResourceManager.GetString("numberformatF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F4 ähnelt.
        /// </summary>
        internal static string numberformatF4 {
            get {
                return ResourceManager.GetString("numberformatF4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F5 ähnelt.
        /// </summary>
        internal static string numberformatF5 {
            get {
                return ResourceManager.GetString("numberformatF5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F6 ähnelt.
        /// </summary>
        internal static string numberformatF6 {
            get {
                return ResourceManager.GetString("numberformatF6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die G6 ähnelt.
        /// </summary>
        internal static string numberformatG6 {
            get {
                return ResourceManager.GetString("numberformatG6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N0 ähnelt.
        /// </summary>
        internal static string numberformatN0 {
            get {
                return ResourceManager.GetString("numberformatN0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N1 ähnelt.
        /// </summary>
        internal static string numberformatN1 {
            get {
                return ResourceManager.GetString("numberformatN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N2 ähnelt.
        /// </summary>
        internal static string numberformatN2 {
            get {
                return ResourceManager.GetString("numberformatN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N3 ähnelt.
        /// </summary>
        internal static string numberformatN3 {
            get {
                return ResourceManager.GetString("numberformatN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N4 ähnelt.
        /// </summary>
        internal static string numberformatN4 {
            get {
                return ResourceManager.GetString("numberformatN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N5 ähnelt.
        /// </summary>
        internal static string numberformatN5 {
            get {
                return ResourceManager.GetString("numberformatN5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N6 ähnelt.
        /// </summary>
        internal static string numberformatN6 {
            get {
                return ResourceManager.GetString("numberformatN6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pentabytes ähnelt.
        /// </summary>
        internal static string pentabytes {
            get {
                return ResourceManager.GetString("pentabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die terabytes ähnelt.
        /// </summary>
        internal static string terabytes {
            get {
                return ResourceManager.GetString("terabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thousand_separator_16 {
            get {
                object obj = ResourceManager.GetObject("thousand_separator_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap value_byte_16 {
            get {
                object obj = ResourceManager.GetObject("value-byte-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap value_gigabyte_16 {
            get {
                object obj = ResourceManager.GetObject("value-gigabyte-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap value_kilobyte_16 {
            get {
                object obj = ResourceManager.GetObject("value-kilobyte-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap value_megabyte_16 {
            get {
                object obj = ResourceManager.GetObject("value-megabyte-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap value_pentabyte_16 {
            get {
                object obj = ResourceManager.GetObject("value-pentabyte-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap value_terabyte_16 {
            get {
                object obj = ResourceManager.GetObject("value-terabyte-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
